CREATE TABLE IF NOT EXISTS vms (
    id SERIAL PRIMARY KEY,
    ram INTEGER NOT NULL,
    cpu INTEGER NOT NULL,
    password TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS disks (
    id SERIAL PRIMARY KEY,
    size INTEGER NOT NULL,
    vm_id INTEGER NOT NULL,
    FOREIGN KEY (vm_id) REFERENCES vms(id) ON DELETE CASCADE
);

CREATE EXTENSION pgcrypto;
